pipeline {
    agent any
    stages {
        stage('one stage-1') {
            steps {
                echo "This is one 1"
                sh 'whoami'
                sh 'ls -la'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete tamilvel'
            }
        }
    }
}
